# Generated by Django 2.0.3 on 2018-03-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('attendence', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=80, unique=True)),
            ],
        ),
    ]
